
sudo: false

language: node_js

node_js:
  - 8
  - 6

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test

after_success:
  - npm run coveralls
  - npm run semantic-release

