
sudo: false

language: node_js

node_js:
  - 8
  - 6

cache:
  directories:
    - node_modules

stages:
  - lint
  - test
  - publish

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run test
      after_success:
        - npm run coveralls
    - stage: publish
      if: branch = master
      script: npm run semantic-release

